name: Build ESP-IDF Tags

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  base-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp32, esp32c3, esp32s2, esp32s3, all]
        idf-version: [release/v4.4, release/v4.3, master]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - ${{ matrix.idf-version }}_${{ matrix.board }} tag
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            ESP_BOARD=${{ matrix.board }}
            ESP_IDF_VERSION=${{ matrix.idf-version }}
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sergiogasquez/esp-idf-env:${{ matrix.idf-version }}_${{ matrix.board }}
